# Joe Nyhan, 24 January 2022

# inserts a blank line between shell prompts
add_newline = true

[character]
# success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# single line prompt
#[line_break]
# disabled = true

[username]
show_always = true

# [time]
#disabled = false

[sudo]
disabled = false
